### ISSUE TITLE
Sign in immediately fails in iOS 13 Beta

### ISSUE THREAD

**Issue by andrewgotow** [okta/okta-oidc-ios#164]
I have an application which uses Okta for authentication. In iOS 11 and 12 everything works as expected, however when running the application under the public beta of iOS 13 sign in immediately fails without presenting a Safari ViewController.

> Authorization Error: The operation couldn't be completed. (org.openid.appauth.general error -3.)

### Expected Behavior

The application initializes a Safari authentication session and presents the sign in ViewController.

### Current Behavior

The application immediately fails, and presents an alert.

**Comment by IldarAbdullin-okta** [comment]
Hi @andrewgotow ,

Thanks for reporting this issue. Underlying AppAuth SDK requires update to support iOS 13
Issue to track: https://github.com/openid/AppAuth-iOS/issues/400

Ildar

**Comment by IldarAbdullin-okta** [comment]
Fixed in [Release 3.4.0](https://github.com/okta/okta-oidc-ios/releases/tag/3.4.0)

**Comment by IldarAbdullin-okta** [comment]
@andrewgotow , did you have a chance to test SDK 3.5.0 with iOS13?

**Comment by volkanbicer** [comment]
This issue seems closed, but I tested SDK 3.5.2, but still see get the same error.  Is there any update on this? @IldarAbdullin-okta

**Comment by akhila-hariharan** [comment]
Hi,

This issue is still there in the latest SDK 3.8.2. Any pointers for the fix ?

**Comment by IldarAbdullin-okta** [comment]
@akhila-hariharan , could you explain what is the issue? Is it reproducible on iOS13 only? Could you check with our sample app as well (https://github.com/okta/samples-ios/tree/master/browser-sign-in)?
