### ISSUE TITLE
OktaNetworkRequestCustomizationDelegate is not used for renew and load from cache

### ISSUE THREAD

**Issue by seanvancity** [okta/okta-oidc-ios#287]
When renewing a session or restoring one from a cold start of the application, the OktaNetworkRequestCustomizationDelegate is not properly assigned and therefore not calling the customizableURLRequest delegate function when attempting to re-auth a user.

Suggested fix from our developer:
Changing line 47 of OIDAuthState+Okta.swift from
`let authState = OKTAuthState(authorizationResponse: authResponse, tokenResponse: tokenResponse)` 
to 
`let authState = OKTAuthState(authorizationResponse: authResponse, tokenResponse: tokenResponse, registrationResponse: nil, delegate: delegate)`

And another issue was identified when resuming the app from when it was previously closed:
 
If I am logged in and restart the app it will try to reinitialize the okta state manager from the keychain (line 140 in AuthCredentials.swift). This works, but the delegate property on OKTAuthState does not get restored. We do pass the config, which contains a reference to the delegate, so I think they just need to set it on the OKTAuthState, once that has been decoded.

**Comment by arvindkrishnakumar-okta** [comment]
@seanvancity Thanks for posting! 

@mikenachbaur-okta Can you help with this?

**Comment by mikenachbaur-okta** [comment]
Thank you @seanvancity, that makes sense to me, thank you for bringing this to our attention! I agree, it seems like we should preserve the delegate in scenarios like this, so I'll check to see if there are other cases where we drop the delegate.

I can't find the AuthCredentials.swift file you reference though, so I can't find that line you mention.

**Comment by seanvancity** [comment]
@mikenachbaur-okta - ah sorry, that's a reference to a credentials file in our code for restoring the state manager after a cold start - so we are looking for guidance there on how to handle that scenario while still including the delegate.

**Comment by mikenachbaur-okta** [comment]
Hmm @seanvancity that's a good observation. I just read through the code some more, and you're right, there's no way to assign the requestCustomizationDelegate to the state manager explicitly, only through the OktaOidcConfig when authenticating, but not for the remainder of the token's lifecycle.

**Comment by mikenachbaur-okta** [comment]
@seanvancity Please take a look at the pull request above, and see if it addresses your issue.

**Comment by seanvancity** [comment]
Looked like a promising PR assuming it solves both of the issues mentioned - is there an ETA on when this will be in the next CocoaPod Release?

**Comment by mikenachbaur-okta** [comment]
I just released version 3.10.2 today that includes these changes, so let me know if it addresses your issues.

**Comment by mikenachbaur-okta** [comment]
@seanvancity I'm going to close this issue out, but if you still have problems or encounter another area where the network request customization delegate is dropped, feel free to reopen it.

**Comment by svdahlberg** [comment]
Hi @mikenachbaur-okta, I have tested this in our application and would like to reopen this issue. The delegate on OKTAuthState is still not set when trying to renew the token after initializing the OktaOidcStateManager by reading from secure storage. 

This is what we are doing: On a cold start of the app we restore the OktaOidcStateManager by calling `OktaOidcStateManager.readFromSecureStorage(for: config)`. This does not set the delegate property on the OKTAuthState, so when we later call `renew(callback:)` on OktaOidcStateManager the delegate method will not be called, since `delegate` is nil. 

Even if I set the property `requestCustomizationDelegate`, that was exposed in this PR, after initializing the state manager from secure storage it does not set the delegate on OKTAuthState, which is used to make the refresh token request. 

Let me know if you need any more details from me.

**Comment by mikenachbaur-okta** [comment]
Thank you @svdahlberg and @seanvancity, this gives me a nicer concrete set of steps to follow through. I'll check this again and will ensure this particular code flow preserves the delegate.

**Comment by mikenachbaur-okta** [comment]
I wanted to provide an update here; ultimately the problem is that NSCoder, and NSKeyedUnarchiver, don't provide any facilities to pass along additional contextual data during the unarchiving process like Swift Codable does, so there's no intuitive way to supply the delegate at that time.

I'm investigating some options to allow the delegate to be updated, without adding risk by exposing the delegate property in the Objective-C code, but I haven't finished my investigation.  I'll update this ticket once a good solution is found.

Thank you for your patience @svdahlberg and @seanvancity!

**Comment by svdahlberg** [comment]
Any updates on this? @mikenachbaur-okta

**Comment by mikenachbaur-okta** [comment]
@svdahlberg I'm coordinating with our engineering team on triaging this issue, so we'll make sure to respond here when we know more.

**Comment by oleggnidets-okta** [comment]
Hi guys,
Please, check out the latest version 3.10.4. It has the public delegate. Let us know whether it fits your needs. Feel free to reopen the issue.
Thanks

**Comment by Gitthatbug** [comment]
I just regained access to a hacked account... And both my iphone se2 and android lg lmk 500 were hacked through the github platform... Using management  

Sent from Yahoo Mail on Android 
 
  On Thu, May 27, 2021 at 3:02 AM, Oleg ***@***.***> wrote:   


Closed #287.
